CCTPMIS.Web/Areas/Enrolment/Controllers/DefaultController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;
using CCTPMIS.Business.Context;
using CCTPMIS.Business.Interfaces;
using CCTPMIS.Business.Model;
using CCTPMIS.Business.Repositories;
using CCTPMIS.Models.AuditTrail;
using CCTPMIS.Models.Email;
using CCTPMIS.Models.Enrolment;
using CCTPMIS.Services;
using ClosedXML.Excel;
using Elmah;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;

namespace CCTPMIS.Web.Areas.Enrolment.Controllers
{
    [Authorize]
    public class DefaultController : Controller
    {
        // private readonly ApplicationDbContext Db;

        // ReSharper disable once InconsistentNaming
        private readonly IEmailService EmailService;

        private readonly ILogService LogService;

        // ReSharper disable once InconsistentNaming
        private readonly IGenericService GenericService;

        public DefaultController(IGenericService genericService, IEmailService emailService, ILogService logService, ApplicationDbContext db)
        {
            GenericService = genericService;
            EmailService = emailService;
            LogService = logService;
        }

        public static DataTable CreateDataTable(IEnumerable source)
        {
            var table = new DataTable();
            int index = 0;
            var properties = new List<PropertyInfo>();
            foreach (var obj in source)
            {
                if (index == 0)
                {
                    foreach (var property in obj.GetType().GetProperties())
                    {
                        if (Nullable.GetUnderlyingType(property.PropertyType) != null)
                        {
                            continue;
                        }

                        properties.Add(property);
                        table.Columns.Add(new DataColumn(property.Name, property.PropertyType));
                    }
                }

                object[] values = new object[properties.Count];
                for (int i = 0; i < properties.Count; i++)
                {
                    values[i] = properties[i].GetValue(obj);
                }
                table.Rows.Add(values);
                index++;
            }
            return table;
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:APPROVAL")]
        public ActionResult Approve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var householdEnrolmentPlan = GenericService.GetOne<HouseholdEnrolmentPlan>(
                x => x.Id == id,
                "ApvByUser,CreatedByUser,ModifiedByUser,Status,EnrolmentGroup,RegGroup,Programme");

            if (householdEnrolmentPlan == null)
            {
                return HttpNotFound();
            }

            return View(householdEnrolmentPlan);
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:APPROVAL")]
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Approve(HouseholdEnrolmentPlan model)
        {
            var userId = int.Parse(User.Identity.GetUserId());

            try
            {
                var databefore = GenericService.GetOne<HouseholdEnrolmentPlan>(x => x.Id == model.Id);

                var parameterNames = "@Id,@UserId";
                var parameterList = new List<ParameterEntity>
                                    {
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "Id",
                                                        model.Id),
                                            },
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "UserId",
                                                        userId),
                                            },
                                    };
                var newModel = GenericService.GetOneBySp<SpIntVm>("ApproveEnrolmentPlan", parameterNames, parameterList);
                TempData["MESSAGE"] = $" The Enrolment successfully Approved.  Kindly Proceed to Generate the Psp File";
                TempData["KEY"] = "success";

                var dataAfter = GenericService.GetOne<HouseholdEnrolmentPlan>(x => x.Id == model.Id);

                var auditTrailVm = new AuditTrailVm {
                    UserId = $"{userId}",
                    Key1 = model.Id,
                    TableName = "HouseholdEnrolmentPlan",
                    ModuleRightCode = "ENROLMENT:APPROVAL",
                    Record = $"[{JsonConvert.SerializeObject(databefore)},{JsonConvert.SerializeObject(dataAfter)}]",
                    WasSuccessful = true,
                    Description = "Household Enrolment Plan Approval Success"
                };
                LogService.AuditTrail(auditTrailVm);
            }
            catch (Exception ex)
            {
                TempData["MESSAGE"] = $" The Enrolment Approval failed. Kindly try again later";
                TempData["KEY"] = "danger";

                ErrorLog.GetDefault(null).Log(new Error(ex));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ClientErrorHandler]
        [AllowAnonymous]
        public ActionResult BeneForEnrolment(int id, int regGroupId)
        {
            var sp = "GetBeneForEnrolment";
            var spParameters = "@ProgrammeId,@RegGroupId";
            var spParameterList = new List<ParameterEntity>
                                      {
                                          new ParameterEntity
                                              {
                                                  ParameterTuple =
                                                      new Tuple<string, object>(
                                                          "ProgrammeId",
                                                          id)
                                              },
                                          new ParameterEntity
                                              {
                                                  ParameterTuple =
                                                      new Tuple<string, object>(
                                                          "RegGroupId",
                                                          regGroupId)
                                              }
                                      };

            var hhEPvm = GenericService.GetOneBySp<HouseholdEnrolmentPlanViewModel>(sp, spParameters, spParameterList);

            return Json(hhEPvm, JsonRequestBehavior.AllowGet);
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:ENTRY")]
        public ActionResult Create()
        {
            ViewBag.ProgrammeId = new SelectList(GenericService.Get<Programme>(), "Id", "Name");
            ViewBag.RegGroupId = new SelectList(
                GenericService.Get<SystemCodeDetail>(x => x.SystemCode.Code == "Registration Group"),
                "Id",
                "Description");
            ViewBag.EnrolmentGroupId = new SelectList(
                GenericService.Get<SystemCodeDetail>(x => x.SystemCode.Code == "Enrolment Group"),
                "Id",
                "Description");

            return View();
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:ENTRY")]
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(HouseholdEnrolmentPlan model)
        {
            var userId = int.Parse(User.Identity.GetUserId());
            var parameterNames =
                "@Id,@ProgrammeId,@RegGroupId,@RegGroupHhs,@BeneHhs,@ExpPlanEqualShare,@ExpPlanPovertyPrioritized,@EnrolmentNumbers,@EnrolmentGroupId,@UserId";
            var parameterList = new List<ParameterEntity>
                                    {
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "Id",
                                                        DBNull.Value),
                                            },
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "ProgrammeId",
                                                        model.ProgrammeId),
                                            },
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "RegGroupId",
                                                        model.RegGroupId),
                                            },
                                        new ParameterEntity
                                            {
                                                ParameterTuple =

CCTPMIS.Web/Areas/Enrolment/Controllers/FilesController.cs
using System.Linq;
using CCTPMIS.Models.Enrolment;

namespace CCTPMIS.Web.Areas.Enrolment.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using Business.Interfaces;
    using Business.Model;
    using CCTPMIS.Models.Email;
    using Microsoft.AspNet.Identity;
    using PagedList;
    using Services;

    [Authorize]
    public class FilesController : Controller
    {
        protected readonly IEmailService EmailService;

        protected readonly IGenericService GenericService;

        public FilesController(IGenericService genericService, IEmailService emailService)
        {
            GenericService = genericService;
            EmailService = emailService;
        }
        [GroupCustomAuthorize(Name = "ENROLMENT:APPROVAL")]
        public ActionResult Approve(int id)
        {
            var file = GenericService.GetOne<FileCreation>(x => x.Id == id);

            return View(file);
        }
        [GroupCustomAuthorize(Name = "ENROLMENT:APPROVAL")]
        [HttpPost]
        public async Task<ActionResult> Approve(FileCreation model)
        {
            var fileService = new FileService();
            var file = await GenericService.GetOneAsync<FileCreation>(x => x.Id == model.Id).ConfigureAwait(false);
            try
            {
                // file.ApprovedBy = int.Parse(User.Identity.GetUserId()); file.ApprovedOn = DateTime.Now;
                file.FileChecksum = fileService.GetChecksum(file.FilePath);
                GenericService.Update(file);

                // get the PSP User List
                var psps = await GenericService.GetAsync<ApplicationUser>(x => x.UserGroup.Name == "PSP", null, "Psps")
                               .ConfigureAwait(false);
                foreach (var psp in psps)
                {
                    await EmailService.SendAsync(
                        new PspEnrolmentFileEmail {
                            FirstName = psp.FirstName,
                            To = psp.DisplayName,
                            FileName = file.Name,
                            Subject = $"New Enrolment File  -  {file.Name} ",
                        }).ConfigureAwait(true);
                }

                TempData["MESSAGE"] = $" The File  {file.Name} was approved  successfully.";
                TempData["KEY"] = "success";
            }
            catch (Exception ex)
            {
                TempData["MESSAGE"] = $"An Error Occured Prior to the Approval of the  {file.Name}." + ex.Message;
                TempData["KEY"] = "danger";
            }

            return RedirectToAction("Index");
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:ENTRY")]
        public ActionResult Create()
        {
            return View();
        }
        [GroupCustomAuthorize(Name = "ENROLMENT:ENTRY")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FileCreation model)
        {
            var userId = int.Parse(User.Identity.GetUserId());
            var parameterNames = "@UserId";
            var parameterList = new List<ParameterEntity>
                                    {
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "UserId",
                                                        userId)
                                            }
                                    };
            var newModel = GenericService.GetOneBySp<FileCreation>("Get_Enrolment_File", parameterNames, parameterList);
            // TempData["ViewModel"] = JsonConvert.SerializeObject(newModel);
            TempData["MESSAGE"] = $" The file  was successfully generated. {newModel.Name} The file must be approved!";
            TempData["KEY"] = "success";
            return RedirectToAction("Index");
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:VIEW")]
        public async Task<ActionResult> Index(int? page)
        {
            var pageSize = int.Parse(WebConfigurationManager.AppSettings["DEFAULT_PAGESIZE"]);
            var pageNum = page ?? 1;

            var userId = int.Parse(User.Identity.GetUserId());
            var files = (await GenericService.GetAsync<FileCreation>(x=>x.Name.Contains("ENROL"), x => x.OrderByDescending(y => y.Id), "CreatedByUser,FileDownloads").ConfigureAwait(true)).ToPagedList(
                pageNum,
                pageSize);
            return View(files);
        }

        [GroupCustomAuthorize(Name = "ENROLMENT:VIEW")]
        public async Task<ActionResult> Details(int id)
        {
            var file = await GenericService.GetOneAsync<FileCreation>(x => x.Id == id,"FileDownloads.DownloadedByUser").ConfigureAwait(false);
            var plans = (await GenericService.GetAsync<HouseholdEnrolmentPlan>(
                    x=>x.FileCreationId == id,
                    x => x.OrderByDescending(y => y.Id),
                    "ApvByUser,CreatedByUser,ModifiedByUser,Status,EnrolmentGroup,RegGroup,Programme,FileCreation")
                .ConfigureAwait(true)).ToList();
            var model = new EnrolmentFileViewModel {
                File = file,
                Plans = plans

            };
            return View(model);
        }
    }
}

CCTPMIS.Web/Areas/Psp/Controllers/EnrolmentController.cs
namespace CCTPMIS.Web.Areas.Psp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using Business.Interfaces;
    using CCTPMIS.Models.Admin;
    using Microsoft.AspNet.Identity;
    using PagedList;
    using Services;

    [Authorize]
    public class EnrolmentController : Controller
    {
        // ReSharper disable once MemberCanBePrivate.Global
        protected readonly IEmailService EmailService;

        // ReSharper disable once MemberCanBePrivate.Global
        protected readonly IGenericService GenericService;

        private readonly ILogService LogService;

        public EnrolmentController(IGenericService genericService, EmailService emailService, ILogService logService)
        {
            GenericService = genericService;
            this.EmailService = emailService;
            LogService = logService;
        }

        // GET: Psp/Enrolment
        [GroupCustomAuthorize(Name = "PSP-ENROLMENT:VIEW")]
        public ActionResult Index(int? page)
        {
            var pageSize = int.Parse(WebConfigurationManager.AppSettings["DEFAULT_PAGESIZE"]);
            var pageNum = page ?? 1;
            var userId = int.Parse(User.Identity.GetUserId());
            const string Spname = "GetEnrolmentPspFiles";
            const string SpParameters = "@UserId";
            var parameterList = new List<ParameterEntity>
                                    {
                                        new ParameterEntity
                                            {
                                                ParameterTuple =
                                                    new Tuple<string, object>(
                                                        "UserId",
                                                        userId)
                                            }
                                    };

            var enrolmentFiles = GenericService
                .GetManyBySp<FilesViewModel>(Spname, SpParameters, parameterList.ToList())
                .ToPagedList(pageNum, pageSize);

            return View(enrolmentFiles);
        }
    }
}

CCTPMIS.Web/Areas/Psp/Views/Enrolment/Create.cshtml
@model dynamic

@{
    ViewBag.Title = "Verify Integrity of the Enrolment File";
}

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label class="btn btn-default btn-file">
                Browse <input type="file" style="display: none" id="EnrolmentFile" accept="text/csv" name="upload"/>
            </label>
            <label>
                <span id="dataFileLabel"> </span>
            </label>
        </div>

    </div>

    <div id="list" class="col-md-12">


    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/encryption")

    <script type="text/javascript">
        (function() {

        });
    </script>


}

CCTPMIS.Web/Areas/Psp/Views/Enrolment/Download.cshtml
@model dynamic
 

CCTPMIS.Web/Areas/Psp/Views/Enrolment/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<CCTPMIS.Models.Admin.FilesViewModel>

@{
    ViewBag.Title = "Enrolment Files";
}

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover table-bordered ">
            <tr>
                <th>
                    File
                </th>

                <th>
                    Date Created
                </th>
                <th>
                    Date Downloaded
                </th>
                <th>
                    Status
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DownloadedOn)
                    </td>
                    <td>
                        @if (item.FileDownloadId == null)
                        {
                            <span>Pending Download</span>
                        }
                        @if (item.DownloadedBy != null)
                        {

                            if (item.DownloadedBy != null)
                            {
                                <span> Verified </span>
                            }
                            else
                            {
                                <span> Pending Verification </span>
                            }
                        }
                    </td>

                    <td>
                        <a class="btn btn-success btn-xs" href="@Url.Action("Verify", "Files", new { id = item.Id, fileDownloadId = item.FileDownloadId })">
                            <i class="fa fa-download"></i> Download / Verify
                        </a>
                        @if (string.IsNullOrEmpty(item.FileChecksum2))
                        {

                        }
                        @*@if (item.DownloadedOn != null && string.IsNullOrEmpty(item.FileChecksum2))
                            {
                                <a class="btn btn-success btn-xs" href="@Url.Action("Verify", new { id = item.Id })">
                                    <i class="icon-search"></i> Verify
                                </a>
                            }*@
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, DistrictId = Request["DistrictId"] }), PagedListRenderOptions.Classic)
    </div>
    <div class="col-md-4">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        Showing  @Model.Count of   @Model.TotalItemCount
    </div>
</div>

CCTPMIS.Web/Areas/Psp/Views/Enrolment/Verify.cshtml
@using Microsoft.AspNet.Identity
@model CCTPMIS.Business.Model.FileCreation

@{
    ViewBag.Title = "Download and Verify the Enrolment File";
}

<div class="row">
    <div class="col-md-12">

        <div class="cards-container box-view">

            <div class="animatedParent animateOnce z-index-50">
                <div class="card animated fadeInUp go">

                    <div class="card-header">

                        <div class="card-photo">
                            <a href="@Url.Action("Download", new { id = Model.Id })">  <i class="fa fa-cloud-download fa-3x"></i><br /> Download </a>
                        </div>
                        <div class="card-short-description">
                            <h5>
                                <span class="user-name">
                                    FILE NAME :  @Html.DisplayFor(model => model.Name)
                                </span>
                            </h5>

                            <h5>
                                <span class="user-name">
                                    FILE CHECKSUM :  @Html.DisplayFor(model => model.FileChecksum)
                                </span>
                            </h5>
                        </div>
                    </div>
                    <div class="card-content">
                        <p>
                            <strong>
                                Kindly browse the File you have downloaded. and verify the Checksum Automatically <br />

                                Note that if the File Checksum is not Verified, you will not be able to submit the Enrolled Members data
                            </strong>
                        </p>

                        <div class="form-group">
                            <label class="btn btn-danger btn-file">
                                VERIFY CHECKSUM <input type="file" style="display: none" id="EnrolmentFile" accept="text/csv,application/x-rar-compressed,application/pdf" name="upload" />
                            </label>
                            <label>
                                <span id="dataFileLabel"> </span>
                            </label>
                        </div>
                        <input type="hidden" name="ServerSha256" value="@Model.FileChecksum" id="ServerSha256" />
                        <input type="hidden" name="UserId" value="@User.Identity.GetUserId()" id="UserId" />
                        <input type="hidden" name="FileCreationId" value="@Model.Id" id="FileCreationId" />
                        <input type="hidden" name="CheckSum" value="" id="CheckSum" />
                    </div>
                    <div id="verificationresults" class="hidden card-header">
                        <div class="card-photo">
                        </div>
                        <div class="card-short-description">
                            <h5>
                                <span class="user-name">
                                    UPLOADED FILE NAME :  <label id="FileName"></label>
                                </span>
                            </h5>

                            <h5>
                                <span class="user-name">
                                    UPLOADED  FILE CHECKSUM :    <label id="FileCheckSum"></label>
                                </span>
                            </h5>
                            <p>
                                <br />
                            </p>

                            <div id="successCheckSum" class="alert hidden alert-success">
                                <strong>Success</strong>
                                <p>
                                    The Checksum has been Verified Successfully
                                </p>
                                <div id="successCheckSumInner"></div>
                            </div>

                            <div id="dangerCheckSum" class="alert hidden alert-danger">
                                <strong>Error</strong>
                                <p>
                                    The Checksum has Failed. Kindly Download the File a new.
                                </p>
                                <div id="dangerCheckSumInner"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="list" class="col-md-12">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a href="@Url.Action("Index", "Enrolment")" class="btn btn-info">
             <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/encryption")

    <script type="text/javascript">
        (function () {

        });
    </script>

}