CCTPMIS.Web/Areas/admin/Controllers/DistrictsController.cs
using CCTPMIS.Models.AuditTrail;
using Newtonsoft.Json;

namespace CCTPMIS.Web.Areas.admin.Controllers
{
    using System;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using Business.Model;
    using Microsoft.AspNet.Identity;
    using PagedList;
    using Services;

    [Authorize]
    [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
    public class DistrictsController : Controller
    {
        protected readonly IGenericService GenericService;
        private readonly ILogService LogService;

        public DistrictsController(IGenericService genericService, ILogService logService)
        {
            GenericService = genericService;
            LogService = logService;
        }

        [GroupCustomAuthorize(Name = "GEOUNITS:ENTRY")]
        // GET: admin/Districts/Create
        public ActionResult Create()
        {
            ViewBag.GeoMasterId = new SelectList(GenericService.Get<GeoMaster>(), "Id", "Name");
            return View();
        }

        // POST: admin/Districts/Create To protect from overposting attacks, please enable the
        // specific properties you want to bind to, for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [GroupCustomAuthorize(Name = "GEOUNITS:ENTRY")]
        public ActionResult Create(
            [Bind(Include = "Id,Name,Code,GeoMasterId,CreatedOn,ModifiedBy,ModifiedOn,CreatedBy")]
            District district)
        {
            var userId = int.Parse(User.Identity.GetUserId());
            district.CreatedBy = userId;
            district.CreatedOn = DateTime.Now;

            if (ModelState.IsValid)
            {
                GenericService.Create(district);
                var auditTrailVm = new AuditTrailVm {
                    UserId = $"{userId}",
                    Key1 = district.Id,
                    TableName = "District",
                    ModuleRightCode = "GEOUNITS:ENTRY",
                    Record = $"{JsonConvert.SerializeObject(district)}",
                    WasSuccessful = true,
                    Description = "District Create Success"
                };
                LogService.AuditTrail(auditTrailVm);
                return RedirectToAction("Index");
            }

            ViewBag.GeoMasterId = new SelectList(GenericService.Get<GeoMaster>(), "Id", "Name", district.GeoMasterId);
            return View(district);
        }

        /*
        // GET: admin/Districts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var district = GenericService.GetOne<District>(
                x => x.Id == id.Value,
                "GeoMaster,Divisions,CreatedByUser,ModifiedByUser");

            if (district == null)
            {
                return HttpNotFound();
            }

            return View(district);
        }

        // POST: admin/Districts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var district = GenericService.GetOne<District>(x => x.Id == id);
            GenericService.Delete(district);

            return RedirectToAction("Index");
        }
        */

        [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
        // GET: admin/Districts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var district = GenericService.GetOne<District>(
                x => x.Id == id.Value,
                "GeoMaster,CountyDistricts,CreatedByUser,ModifiedByUser");
            if (district == null)
            {
                return HttpNotFound();
            }

            return View(district);
        }

        /*
                [GroupCustomAuthorize(Name = "GEOUNITS:MODIFIER")]
                // GET: admin/Districts/Edit/5
                public ActionResult Edit(int? id)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }

                    var district = GenericService.GetOne<District>(x => x.Id == id.Value, string.Empty);

                    if (district == null)
                    {
                        return HttpNotFound();
                    }

                    ViewBag.GeoMasterId = new SelectList(GenericService.Get<GeoMaster>(), "Id", "Name", district.GeoMasterId);
                    return View(district);
                }

                // POST: admin/Districts/Edit/5 To protect from overposting attacks, please enable
                // the specific properties you want to bind to, for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
                [HttpPost]
                [ValidateAntiForgeryToken]
                [GroupCustomAuthorize(Name = "GEOUNITS:MODIFIER")]
                public ActionResult Edit(
                    [Bind(Include = "Id,Name,Code,GeoMasterId,CreatedOn,ModifiedBy,ModifiedOn,CreatedBy")]
                    District district)
                {
                    district.ModifiedBy = int.Parse(User.Identity.GetUserId());
                    district.ModifiedOn = DateTime.Now;

                    if (ModelState.IsValid)
                    {
                        GenericService.Update(district);
                        return RedirectToAction("Index");
                    }

                    ViewBag.GeoMasterId = new SelectList(GenericService.Get<GeoMaster>(), "Id", "Name", district.GeoMasterId);
                    return View(district);
                }
                */

        // GET: admin/Districts
        [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
        public async Task<ActionResult> Index(int? page, int? geoMasterId)
        {
            var pageSize = int.Parse(WebConfigurationManager.AppSettings["DEFAULT_PAGESIZE"]);
            var pageNum = page ?? 1;
            IPagedList<District> districts = null;
            districts = geoMasterId.HasValue
                            ? (await GenericService.GetAsync<District>(
                                   x => x.GeoMasterId == geoMasterId,
                                   x => x.OrderBy(y => y.Code),
                                   "CreatedByUser,ModifiedByUser,GeoMaster")).ToPagedList(pageNum, pageSize)
                            : (await GenericService.GetAsync<District>(
                                   null,
                                   x => x.OrderBy(y => y.Code),
                                   "CreatedByUser,ModifiedByUser,GeoMaster")).ToPagedList(pageNum, pageSize);
            ViewBag.GeoMasterId = new SelectList(GenericService.GetAll<GeoMaster>(), "Id", "Name");
            return View(districts);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

CCTPMIS.Web/Areas/admin/Controllers/GeoMastersController.cs
using CCTPMIS.Models.AuditTrail;
using Newtonsoft.Json;

namespace CCTPMIS.Web.Areas.admin.Controllers
{
    using System;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using Business.Model;
    using Microsoft.AspNet.Identity;
    using PagedList;
    using Services;

    [Authorize]
    public class GeoMastersController : Controller
    {
        public IGenericService GenericService;
        private readonly ILogService LogService;

        public GeoMastersController(IGenericService genericService, ILogService logService)
        {
            GenericService = genericService;
            LogService = logService;
        }

        [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
        public ActionResult Counties(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var geoMaster = GenericService.GetOne<GeoMaster>(
                x => x.Id == id.Value,
                "CreatedByUser,ModifiedByUser,Counties");

            // GeoMasterService.GetGeoMasterAsync(id.Value);
            if (geoMaster == null)
            {
                return HttpNotFound();
            }

            return View(geoMaster);
        }

        // GET: admin/GeoMasters/Create
        [GroupCustomAuthorize(Name = "GEOUNITS:ENTRY")]
        public ActionResult Create()
        {
            return View();
        }

        [GroupCustomAuthorize(Name = "GEOUNITS:ENTRY")]
        // POST: admin/GeoMasters/Create To protect from overposting attacks, please enable the
        // specific properties you want to bind to, for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Year,IsActive,Description")]   GeoMaster geoMaster)
        {
            var userId = int.Parse(User.Identity.GetUserId());
            geoMaster.CreatedBy = userId;
            geoMaster.CreatedOn = DateTime.Now;

            if (ModelState.IsValid)
            {
                GenericService.Create<GeoMaster>(geoMaster);
                LogService.AuditTrail(new AuditTrailVm {
                    UserId = $"{userId}",
                    Key1 = geoMaster.Id,
                    TableName = "GeoMaster",
                    ModuleRightCode = "GEOUNITS:ENTRY",
                    Record = $"{JsonConvert.SerializeObject(geoMaster)}",
                    WasSuccessful = true,
                    Description = "GeoMaster Created Success"
                });
                return RedirectToAction(nameof(Index));
            }

            return View(geoMaster);
        }

        /*
        // GET: admin/GeoMasters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var geoMaster = GenericService.GetOne<GeoMaster>(x => x.Id == id.Value);
            if (geoMaster == null)
            {
                return HttpNotFound();
            }

            return View(geoMaster);
        }

        // POST: admin/GeoMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            return RedirectToAction("Index");
        }
        */

        [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var geoMaster = GenericService.GetOne<GeoMaster>(x => x.Id == id.Value, "CreatedByUser,ModifiedByUser");

            // GeoMasterService.GetGeoMasterAsync(id.Value);
            if (geoMaster == null)
            {
                return HttpNotFound();
            }

            return View(geoMaster);
        }

        [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
        public ActionResult Districts(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var geoMaster = GenericService.GetOne<GeoMaster>(
                x => x.Id == id.Value,
                "CreatedByUser,ModifiedByUser,Districts");

            // GeoMasterService.GetGeoMasterAsync(id.Value);
            if (geoMaster == null)
            {
                return HttpNotFound();
            }

            return View(geoMaster);
        }

        /* [GroupCustomAuthorize(Name = "GEOUNITS:MODIFIER")]
         // GET: admin/GeoMasters/Edit/5
         public ActionResult Edit(int? id)
         {
             if (id == null)
             {
                 return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
             }

             // GeoMaster geoMaster = GeoMasterService.GetGeoMasterAsync(id.Value);
             var geoMaster = GenericService.GetOne<GeoMaster>(x => x.Id == id.Value);

             if (geoMaster == null)
             {
                 return HttpNotFound();
             }

             return View(geoMaster);
         }

         // POST: admin/GeoMasters/Edit/5 To protect from overposting attacks, please enable the
         // specific properties you want to bind to, for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
         [GroupCustomAuthorize(Name = "GEOUNITS:MODIFIER")]
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Edit(
             [Bind(Include = "Id,Name,Year,IsActive,Description,CreatedBy,CreatedOn,ModifiedOn,ModifiedBy")]
             GeoMaster geoMaster)
         {
             geoMaster.ModifiedBy = int.Parse(User.Identity.GetUserId());
             geoMaster.ModifiedOn = DateTime.Now;

             if (ModelState.IsValid)
             {
                 GenericService.Update<GeoMaster>(geoMaster);

                 return RedirectToAction(nameof(Index));
             }

             return View(geoMaster);
         }
         */

        [GroupCustomAuthorize(Name = "GEOUNITS:VIEW")]
        // GET: admin/GeoMasters
        public async Task<ActionResult> Index(int? page)
        {
            var pageSize = int.Parse(WebConfigurationManager.AppSettings["DEFAULT_PAGESIZE"]);
            var pageNum = page ?? 1;
            var geoMasters =
                (await GenericService.GetAsync<GeoMaster>(
                     null,
                     x => x.OrderBy(y => y.Name),
                     "CreatedByUser,ModifiedByUser")).ToPagedList(pageNum, pageSize);
            return View(geoMasters);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }

            base.Dispose(disposing);
        }
    }
}

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Counties.cshtml
@model CCTPMIS.Business.Model.GeoMaster

@{
    ViewBag.Title = Model.Name + "    Counties";
}

<div class="row">
    <div class="col-md-12">
        @Html.Partial("_CommonDetails", Model)
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        <table class="table table-bordered table-striped table-striped">
            <tr>

                <th>
                    Name
                </th>
                <th>
                    Code
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                @*<th></th>*@
            </tr>

            @foreach (var item in Model.Counties)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedByUser.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedByUser.FirstName)
                    </td>
                    @*<td>
                </td>*@
                </tr>
            }
        </table>
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Create.cshtml
@model CCTPMIS.Business.Model.GeoMaster

@{
    ViewBag.Title = "Create GeoMaster ";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, string.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, string.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.CreatedOn)
                @Html.HiddenFor(model => model.ModifiedBy)
                @Html.HiddenFor(model => model.ModifiedOn)
                @Html.HiddenFor(model => model.CreatedBy)

                <div class="form-group">
                    @Html.Partial("Common/_CreateFooter")
                </div>
            </div>
        }
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Delete.cshtml
@model CCTPMIS.Business.Model.GeoMaster

@{
    ViewBag.Title = "Delete GeoMaster " + Model.Name;
}

<div class="row">
    <div class="col-md-12">
        <h3>Are you sure you want to delete this?</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @Html.Partial("_CommonDetails", Model)
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                @Html.Partial("Common/_DeleteFooter", Model.Id)
            </div>
        }
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Details.cshtml
@model CCTPMIS.Business.Model.GeoMaster

@{
    ViewBag.Title = "GeoMaster Details";
}

<div class="row">
    <div class="col-md-12">
        @Html.Partial("_CommonDetails", Model)
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="@Url.Action("Index")" class="btn    btn-primary"><i class="fa fa-navicon"></i> Back to List</a>
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Districts.cshtml
@model CCTPMIS.Business.Model.GeoMaster

@{
    ViewBag.Title = Model.Name + "    Districts";
}

<div class="row">
    <div class="col-md-12">
        @Html.Partial("_CommonDetails")
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        <table class="table table-bordered table-striped table-striped">
            <tr>

                <th>
                    Name
                </th>
                <th>
                    Code
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                @*<th></th>*@
            </tr>

            @foreach (var item in Model.Districts)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedByUser.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedByUser.FirstName)
                    </td>
                    @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>*@
                </tr>
            }
        </table>
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Edit.cshtml
@model CCTPMIS.Business.Model.GeoMaster

@{
    ViewBag.Title = "Edit GeoMaster";
}

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, string.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, string.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.CreatedOn)
                @Html.HiddenFor(model => model.ModifiedBy)
                @Html.HiddenFor(model => model.ModifiedOn)
                @Html.HiddenFor(model => model.CreatedBy)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.Partial("Common/_EditFooter", Model.Id)
                    </div>
                </div>
            </div>
        }
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/Index.cshtml
@model PagedList.IPagedList<CCTPMIS.Business.Model.GeoMaster>
@using PagedList.Mvc
@{
    ViewBag.Title = "Geo Masters";
}

<div class="row">
    <div class="col-md-12">
        <div class="m-tb-30 pull-right ">
            @Html.Partial("Common/_AddButton")
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped">
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Description
                </th>
                @*<th>
                    Created On
                </th>
                <th>
                    Modified By
                </th>
                <th>
                    Modified On
                </th>
                <th>
                    Created By
                </th>*@
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedByUser.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedByUser.FirstName)
                    </td>*@
                    <td>
                        @Html.Partial("Common/_GridDIcons", item.Id)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), PagedListRenderOptions.Classic)
    </div>
    <div class="col-md-4">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        Showing @Model.Count of @Model.TotalItemCount
    </div>
</div>

CCTPMIS.Web/Areas/admin/Views/GeoMasters/_CommonDetails.cshtml
@model CCTPMIS.Business.Model.GeoMaster

<table class="table table-bordered table-striped table-hover">
    <tbody>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <td>
                @Html.DisplayFor(model => model.Name)
            </td>

            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <td>
                @Html.DisplayFor(model => model.Description)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>

            <td>
                @Html.DisplayFor(model => model.CreatedOn)
            </td>

            <th>
                @Html.DisplayNameFor(model => model.ModifiedBy)
            </th>

            <td>
                @Html.DisplayFor(model => model.ModifiedByUser.DisplayName)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </th>

            <td>
                @Html.DisplayFor(model => model.ModifiedOn)
            </td>

            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>

            <td>
                @Html.DisplayFor(model => model.CreatedByUser.DisplayName)
            </td>
        </tr>
        <tr>
            <td>
                <a href="@Url.Action("Counties", "GeoMasters" , new { id = Model.Id })" class="btn btn-info btn-sm ">  <i class="fa fa-eye"></i> Counties </a>
            </td>
            <td>
                <a href="@Url.Action("Districts", "GeoMasters", new {id = Model.Id})" class="btn btn-info btn-sm ">  <i class="fa fa-eye"></i> Districts </a>
            </td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>